using backend.Data;
using backend.Middleware;
using backend.Models;
using DotNetEnv;
using Microsoft.AspNetCore.HttpOverrides;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

// Keep local date-only form submissions compatible with timestamptz columns.
AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);

Env.NoClobber().Load(Path.Combine(Directory.GetCurrentDirectory(), ".env"));
var builder = WebApplication.CreateBuilder(args);
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");
var allowedOrigins = builder.Configuration.GetSection("Cors:AllowedOrigins").Get<string[]>() ?? [];
var applyMigrations = builder.Configuration.GetValue<bool>("StartupTasks:ApplyMigrations");
var seedPredictions = builder.Configuration.GetValue<bool>("StartupTasks:SeedPredictions");

// Add DbContext
builder.Services.AddDbContext<IntexDbContext>(options =>
    options.UseNpgsql(connectionString));

// Add Identity services
builder.Services
    .AddIdentity<ApplicationUser, IdentityRole>(options =>
    {
        // Lockout settings
        options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(15);
        options.Lockout.MaxFailedAccessAttempts = 5;
        
        // User settings
        options.User.RequireUniqueEmail = true;
    })
    .AddEntityFrameworkStores<IntexDbContext>()
    .AddDefaultTokenProviders();

builder.Services.Configure<IdentityOptions>(options =>
{
    options.Password.RequireDigit = false;
    options.Password.RequireLowercase = false;
    options.Password.RequireNonAlphanumeric = false;
    options.Password.RequireUppercase = false;
    options.Password.RequiredLength = 14;
    options.Password.RequiredUniqueChars = 1;
});

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.AddHsts(options =>
{
    options.MaxAge = TimeSpan.FromDays(180);
    options.IncludeSubDomains = true;
    options.Preload = false;
});

builder.Services.Configure<ForwardedHeadersOptions>(options =>
{
    options.ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
    options.KnownIPNetworks.Clear();
    options.KnownProxies.Clear();
});

builder.Services.AddCors(options =>
{
    options.AddPolicy("AppCors", policy =>
    {
        if (allowedOrigins.Length > 0)
        {
            policy.WithOrigins(allowedOrigins)
                .AllowAnyHeader()
                .AllowAnyMethod()
                .AllowCredentials();
            return;
        }

        // Safe local fallback for development if config is missing.
        policy.WithOrigins("http://localhost:5173", "https://localhost:5173")
            .AllowAnyHeader()
            .AllowAnyMethod()
            .AllowCredentials();
    });
});

var app = builder.Build();

// Seed database with roles
using (var scope = app.Services.CreateScope())
{
    var logger = scope.ServiceProvider.GetRequiredService<ILoggerFactory>().CreateLogger("Startup");

    try
    {
        var db = scope.ServiceProvider.GetRequiredService<IntexDbContext>();

        if (applyMigrations)
        {
            try
            {
                await db.Database.MigrateAsync();
                logger.LogInformation("Applied database migrations.");
            }
            catch (Exception migrationEx)
            {
                logger.LogError(migrationEx, "Database migration failed; continuing startup.");
            }
        }

        var roleManager = scope.ServiceProvider.GetRequiredService<RoleManager<IdentityRole>>();
        var roles = new[] { "Admin", "Donor" };

        foreach (var role in roles)
        {
            if (!await roleManager.RoleExistsAsync(role))
            {
                await roleManager.CreateAsync(new IdentityRole(role));
            }
        }

        if (seedPredictions)
        {
            await PredictionSeedService.SeedAsync(db);
            logger.LogInformation("Seeded prediction tables.");
        }

        await EnsureBlogPostsTableAsync(db);
        await BlogSeedData.SeedAsync(db);
        logger.LogInformation("Seeded blog posts.");
    }
    catch (Exception ex)
    {
        logger.LogError(ex, "Startup data initialization failed; app will continue running.");
    }
}

static async Task EnsureBlogPostsTableAsync(IntexDbContext db)
{
    const string createBlogPostsTableSql = """
        CREATE TABLE IF NOT EXISTS blog_posts (
            blog_post_id integer GENERATED BY DEFAULT AS IDENTITY,
            title text NOT NULL,
            data text NOT NULL,
            categories text NOT NULL,
            comments text NOT NULL,
            text text NOT NULL,
            CONSTRAINT "PK_blog_posts" PRIMARY KEY (blog_post_id)
        );
        """;

    await db.Database.ExecuteSqlRawAsync(createBlogPostsTableSql);
}

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}
else
{
    app.UseHsts();
}

app.UseCors("AppCors");
app.UseForwardedHeaders();

app.UseHttpsRedirection();
app.UseSecurityHeaders();

// Add authentication and authorization middleware
app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();

app.Run();
